{
 "title": "Netology Dash",
 "time": { "from": "2022-11-12T23:52:24.506Z", "to": "2022-11-13T11:52:24.506Z" },
 "panels": [
  {
   "title": "CPU Load Time, %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg without(cpu) (rate(node_cpu_seconds_total{job=\"nodeexporter\", mode=\"idle\"}[1m])) * 100) ",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPULA1" },
    { "expr": "node_load5", "legendFormat": "CPULA5" },
    { "expr": "node_load15", "legendFormat": "CPULA15" }
   ]
  },
  {
   "title": "Memory Available, GB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"nodeexporter\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Disk available, GB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint='/', job=\"nodeexporter\"}",
     "legendFormat": "Disk Available, GB"
    }
   ]
  }
 ]
}